// import '../models/profile.dart';
// import '../models/reservation.dart';
// import '../models/space.dart';
// import '../models/community.dart';
// import '../models/branch.dart';

// import '../models/time_slot.dart';

// class FakeData {
//   static int _idCounter = 1;

//   static String generateId() {
//     return 'id_${_idCounter++}';
//   }

//   // 현재 사용자
//   static final Profile currentProfile = Profile(
//     id: 'user_1',
//     name: '김기도',
//     email: 'pray@example.com',
//     phone: '010-1234-5678',
//     createdAt: DateTime.now().subtract(const Duration(days: 30)),
//     lastLoginAt: DateTime.now(),
//     updatedAt: DateTime.now(),
//   );

//   // 지점 데이터
//   static final List<Branch> branches = [
//     Branch(
//       id: 'branch_1',
//       name: '강남 기도실',
//       address: '서울특별시 강남구 테헤란로 123',
//       phone: '02-1234-5678',
//       description:
//           '강남역 3번 출구에서 도보 5분 거리에 위치한 프리미엄 기도실입니다. 조용하고 평화로운 분위기에서 기도하실 수 있습니다.',
//       latitude: 37.5665,
//       longitude: 127.0018,
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//       ],
//       amenities: ['Wi-Fi', '에어컨', '히터', '정수기', '화장실', '주차장'],
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       isActive: true,
//       managerName: '박관리',
//       managerPhone: '010-1111-2222',
//       createdAt: DateTime.now().subtract(const Duration(days: 365)),
//       updatedAt: DateTime.now(),
//     ),
//     Branch(
//       id: 'branch_2',
//       name: '홍대 기도실',
//       address: '서울특별시 마포구 홍대로 456',
//       phone: '02-2345-6789',
//       description: '홍대입구역 근처에 위치한 젊은 감각의 기도실입니다. 24시간 운영으로 언제든지 이용하실 수 있습니다.',
//       latitude: 37.5575,
//       longitude: 126.9250,
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//       ],
//       amenities: ['Wi-Fi', '에어컨', '히터', '정수기', '화장실', '24시간 운영'],
//       operatingHours: {
//         '월': {'open': '00:00', 'close': '23:59'},
//         '화': {'open': '00:00', 'close': '23:59'},
//         '수': {'open': '00:00', 'close': '23:59'},
//         '목': {'open': '00:00', 'close': '23:59'},
//         '금': {'open': '00:00', 'close': '23:59'},
//         '토': {'open': '00:00', 'close': '23:59'},
//         '일': {'open': '00:00', 'close': '23:59'},
//       },
//       isActive: true,
//       managerName: '이관리',
//       managerPhone: '010-2222-3333',
//       createdAt: DateTime.now().subtract(const Duration(days: 300)),
//       updatedAt: DateTime.now(),
//     ),
//     Branch(
//       id: 'branch_3',
//       name: '부산 해운대 기도실',
//       address: '부산광역시 해운대구 해운대로 789',
//       phone: '051-3456-7890',
//       description:
//           '해운대 해변 근처에 위치한 바다가 보이는 기도실입니다. 평화로운 바다 풍경을 바라보며 기도하실 수 있습니다.',
//       latitude: 35.1586,
//       longitude: 129.1603,
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//       ],
//       amenities: ['Wi-Fi', '에어컨', '히터', '정수기', '화장실', '바다 전망'],
//       operatingHours: {
//         '월': {'open': '07:00', 'close': '21:00'},
//         '화': {'open': '07:00', 'close': '21:00'},
//         '수': {'open': '07:00', 'close': '21:00'},
//         '목': {'open': '07:00', 'close': '21:00'},
//         '금': {'open': '07:00', 'close': '21:00'},
//         '토': {'open': '08:00', 'close': '18:00'},
//         '일': {'open': '08:00', 'close': '18:00'},
//       },
//       isActive: true,
//       managerName: '최관리',
//       managerPhone: '010-3333-4444',
//       createdAt: DateTime.now().subtract(const Duration(days: 200)),
//       updatedAt: DateTime.now(),
//     ),
//     Branch(
//       id: 'branch_4',
//       name: '대치 기도실',
//       address: '서울특별시 강남구 대치동 123-45',
//       phone: '02-4567-8901',
//       description: '대치동 학원가에 위치한 조용한 기도실입니다. 학생들과 직장인들이 많이 이용하는 프리미엄 기도실입니다.',
//       latitude: 37.5012,
//       longitude: 127.0589,
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//       ],
//       amenities: ['Wi-Fi', '에어컨', '히터', '정수기', '화장실', '주차장', '스터디룸'],
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '23:00'},
//         '화': {'open': '06:00', 'close': '23:00'},
//         '수': {'open': '06:00', 'close': '23:00'},
//         '목': {'open': '06:00', 'close': '23:00'},
//         '금': {'open': '06:00', 'close': '23:00'},
//         '토': {'open': '07:00', 'close': '22:00'},
//         '일': {'open': '07:00', 'close': '22:00'},
//       },
//       isActive: true,
//       managerName: '김관리',
//       managerPhone: '010-4444-5555',
//       createdAt: DateTime.now().subtract(const Duration(days: 150)),
//       updatedAt: DateTime.now(),
//     ),
//     Branch(
//       id: 'branch_5',
//       name: '강동 기도실',
//       address: '서울특별시 강동구 천호대로 456-78',
//       phone: '02-5678-9012',
//       description: '강동구 중심가에 위치한 가족 친화적인 기도실입니다. 넓은 공간과 편안한 분위기를 제공합니다.',
//       latitude: 37.5301,
//       longitude: 127.1234,
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//       ],
//       amenities: ['Wi-Fi', '에어컨', '히터', '정수기', '화장실', '주차장', '휴게실', '카페테리아'],
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       isActive: true,
//       managerName: '정관리',
//       managerPhone: '010-5555-6666',
//       createdAt: DateTime.now().subtract(const Duration(days: 100)),
//       updatedAt: DateTime.now(),
//     ),
//     Branch(
//       id: 'branch_6',
//       name: '부산해운대 기도실',
//       address: '부산광역시 해운대구 우동 789-12',
//       phone: '051-6789-0123',
//       description: '해운대 해변 바로 앞에 위치한 최고급 기도실입니다. 바다 전망과 함께 프리미엄 기도 경험을 제공합니다.',
//       latitude: 35.1586,
//       longitude: 129.1603,
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
//       ],
//       amenities: [
//         'Wi-Fi',
//         '에어컨',
//         '히터',
//         '정수기',
//         '화장실',
//         '바다 전망',
//         '테라스',
//         '프리미엄 시설'
//       ],
//       operatingHours: {
//         '월': {'open': '07:00', 'close': '22:00'},
//         '화': {'open': '07:00', 'close': '22:00'},
//         '수': {'open': '07:00', 'close': '22:00'},
//         '목': {'open': '07:00', 'close': '22:00'},
//         '금': {'open': '07:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       isActive: true,
//       managerName: '박해운',
//       managerPhone: '010-6666-7777',
//       createdAt: DateTime.now().subtract(const Duration(days: 50)),
//       updatedAt: DateTime.now(),
//     ),
//   ];

//   // 공간 데이터 (지점별)
//   static final List<Space> spaces = [
//     // 강남 지점 공간들
//     Space(
//       id: 'space_1',
//       branchId: 'branch_1',
//       name: '1인 기도실 A',
//       description: '1인용 프리미엄 기도실입니다. 조용하고 집중할 수 있는 환경을 제공합니다.',
//       capacity: 1,
//       pricePerHour: 5000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: true,
//       category: '1인실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 365)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_2',
//       branchId: 'branch_1',
//       name: '2인 기도실 B',
//       description: '2인용 기도실입니다. 부부나 친구와 함께 기도하실 수 있습니다.',
//       capacity: 2,
//       pricePerHour: 8000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '소파'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: true,
//       category: '2인실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 365)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_3',
//       branchId: 'branch_1',
//       name: '그룹 기도실 C',
//       description: '최대 6명까지 이용 가능한 그룹 기도실입니다. 소그룹 모임에 적합합니다.',
//       capacity: 6,
//       pricePerHour: 15000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '프로젝터', '화이트보드'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: false,
//       category: '그룹실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 365)),
//       updatedAt: DateTime.now(),
//     ),
//     // 홍대 지점 공간들
//     Space(
//       id: 'space_4',
//       branchId: 'branch_2',
//       name: '1인 기도실 D',
//       description: '24시간 운영되는 1인용 기도실입니다.',
//       capacity: 1,
//       pricePerHour: 4000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: true,
//       category: '1인실',
//       operatingHours: {
//         '월': {'open': '00:00', 'close': '23:59'},
//         '화': {'open': '00:00', 'close': '23:59'},
//         '수': {'open': '00:00', 'close': '23:59'},
//         '목': {'open': '00:00', 'close': '23:59'},
//         '금': {'open': '00:00', 'close': '23:59'},
//         '토': {'open': '00:00', 'close': '23:59'},
//         '일': {'open': '00:00', 'close': '23:59'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 300)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_5',
//       branchId: 'branch_2',
//       name: '2인 기도실 E',
//       description: '24시간 운영되는 2인용 기도실입니다.',
//       capacity: 2,
//       pricePerHour: 7000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '소파'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: true,
//       category: '2인실',
//       operatingHours: {
//         '월': {'open': '00:00', 'close': '23:59'},
//         '화': {'open': '00:00', 'close': '23:59'},
//         '수': {'open': '00:00', 'close': '23:59'},
//         '목': {'open': '00:00', 'close': '23:59'},
//         '금': {'open': '00:00', 'close': '23:59'},
//         '토': {'open': '00:00', 'close': '23:59'},
//         '일': {'open': '00:00', 'close': '23:59'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 300)),
//       updatedAt: DateTime.now(),
//     ),
//     // 부산 지점 공간들
//     Space(
//       id: 'space_6',
//       branchId: 'branch_3',
//       name: '바다 전망 기도실 F',
//       description: '해운대 바다가 보이는 프리미엄 기도실입니다.',
//       capacity: 1,
//       pricePerHour: 6000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '바다 전망'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: true,
//       category: '1인실',
//       operatingHours: {
//         '월': {'open': '07:00', 'close': '21:00'},
//         '화': {'open': '07:00', 'close': '21:00'},
//         '수': {'open': '07:00', 'close': '21:00'},
//         '목': {'open': '07:00', 'close': '21:00'},
//         '금': {'open': '07:00', 'close': '21:00'},
//         '토': {'open': '08:00', 'close': '18:00'},
//         '일': {'open': '08:00', 'close': '18:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 200)),
//       updatedAt: DateTime.now(),
//     ),
//     // 대치 지점 공간들
//     Space(
//       id: 'space_7',
//       branchId: 'branch_4',
//       name: '스터디 기도실 G',
//       description: '학생들을 위한 조용한 스터디 기도실입니다. 집중하기 좋은 환경을 제공합니다.',
//       capacity: 1,
//       pricePerHour: 4500,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '책상', '의자'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: true,
//       category: '1인실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '23:00'},
//         '화': {'open': '06:00', 'close': '23:00'},
//         '수': {'open': '06:00', 'close': '23:00'},
//         '목': {'open': '06:00', 'close': '23:00'},
//         '금': {'open': '06:00', 'close': '23:00'},
//         '토': {'open': '07:00', 'close': '22:00'},
//         '일': {'open': '07:00', 'close': '22:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 150)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_8',
//       branchId: 'branch_4',
//       name: '그룹 스터디실 H',
//       description: '소그룹 스터디와 기도를 함께할 수 있는 공간입니다.',
//       capacity: 4,
//       pricePerHour: 12000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '화이트보드', '프로젝터'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: true,
//       category: '그룹실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '23:00'},
//         '화': {'open': '06:00', 'close': '23:00'},
//         '수': {'open': '06:00', 'close': '23:00'},
//         '목': {'open': '06:00', 'close': '23:00'},
//         '금': {'open': '06:00', 'close': '23:00'},
//         '토': {'open': '07:00', 'close': '22:00'},
//         '일': {'open': '07:00', 'close': '22:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 150)),
//       updatedAt: DateTime.now(),
//     ),
//     // 강동 지점 공간들
//     Space(
//       id: 'space_9',
//       branchId: 'branch_5',
//       name: '가족 기도실 I',
//       description: '가족이 함께 이용할 수 있는 넓은 기도실입니다.',
//       capacity: 4,
//       pricePerHour: 10000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '소파', '테이블'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: true,
//       category: '가족실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 100)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_10',
//       branchId: 'branch_5',
//       name: '커뮤니티 기도실 J',
//       description: '커뮤니티 모임을 위한 대형 기도실입니다.',
//       capacity: 8,
//       pricePerHour: 18000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '프로젝터', '스피커', '마이크'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: false,
//       category: '커뮤니티실',
//       operatingHours: {
//         '월': {'open': '06:00', 'close': '22:00'},
//         '화': {'open': '06:00', 'close': '22:00'},
//         '수': {'open': '06:00', 'close': '22:00'},
//         '목': {'open': '06:00', 'close': '22:00'},
//         '금': {'open': '06:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 100)),
//       updatedAt: DateTime.now(),
//     ),
//     // 부산해운대 지점 공간들
//     Space(
//       id: 'space_11',
//       branchId: 'branch_6',
//       name: '프리미엄 바다뷰 기도실 K',
//       description: '해운대 바다를 한눈에 볼 수 있는 최고급 기도실입니다.',
//       capacity: 1,
//       pricePerHour: 8000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '바다 전망', '테라스', '프리미엄 시설'],
//       images: [
//         'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
//       ],
//       isAvailable: true,
//       category: '프리미엄실',
//       operatingHours: {
//         '월': {'open': '07:00', 'close': '22:00'},
//         '화': {'open': '07:00', 'close': '22:00'},
//         '수': {'open': '07:00', 'close': '22:00'},
//         '목': {'open': '07:00', 'close': '22:00'},
//         '금': {'open': '07:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 50)),
//       updatedAt: DateTime.now(),
//     ),
//     Space(
//       id: 'space_12',
//       branchId: 'branch_6',
//       name: '커플 바다뷰 기도실 L',
//       description: '커플을 위한 로맨틱한 바다 전망 기도실입니다.',
//       capacity: 2,
//       pricePerHour: 12000,
//       amenities: ['에어컨', '히터', '조명 조절', '방음 시설', '바다 전망', '테라스', '로맨틱 조명'],
//       images: [
//         'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
//       ],
//       isAvailable: true,
//       category: '커플실',
//       operatingHours: {
//         '월': {'open': '07:00', 'close': '22:00'},
//         '화': {'open': '07:00', 'close': '22:00'},
//         '수': {'open': '07:00', 'close': '22:00'},
//         '목': {'open': '07:00', 'close': '22:00'},
//         '금': {'open': '07:00', 'close': '22:00'},
//         '토': {'open': '08:00', 'close': '20:00'},
//         '일': {'open': '08:00', 'close': '20:00'},
//       },
//       createdAt: DateTime.now().subtract(const Duration(days: 50)),
//       updatedAt: DateTime.now(),
//     ),
//   ];

//   // 예약 데이터 (지점별)
//   static final List<Reservation> reservations = [
//     Reservation(
//       id: 'reservation_1',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_1',
//       branchName: '강남 기도실',
//       spaceId: 'space_1',
//       spaceName: '1인 기도실 A',
//       date: DateTime.now(),
//       timeSlot: '09:00-11:00',
//       duration: 120,
//       price: 10000,
//       discountedPrice: 9500,
//       status: ReservationStatus.reserved,
//       notes: '조용한 시간에 기도하고 싶습니다.',
//       createdAt: DateTime.now().subtract(const Duration(hours: 2)),
//       updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
//     ),
//     Reservation(
//       id: 'reservation_2',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_2',
//       branchName: '홍대 기도실',
//       spaceId: 'space_4',
//       spaceName: '1인 기도실 D',
//       date: DateTime.now().add(const Duration(days: 1)),
//       timeSlot: '14:00-16:00',
//       duration: 120,
//       price: 8000,
//       discountedPrice: 7600,
//       status: ReservationStatus.reserved,
//       notes: null,
//       createdAt: DateTime.now().subtract(const Duration(hours: 1)),
//       updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
//     ),
//     Reservation(
//       id: 'reservation_3',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_1',
//       branchName: '강남 기도실',
//       spaceId: 'space_2',
//       spaceName: '2인 기도실 B',
//       date: DateTime.now().subtract(const Duration(days: 1)),
//       timeSlot: '10:00-12:00',
//       duration: 120,
//       price: 16000,
//       discountedPrice: 15200,
//       status: ReservationStatus.completed,
//       notes: '부부 기도 시간',
//       createdAt: DateTime.now().subtract(const Duration(days: 2)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 1)),
//     ),
//     Reservation(
//       id: 'reservation_4',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_4',
//       branchName: '대치 기도실',
//       spaceId: 'space_7',
//       spaceName: '스터디 기도실 G',
//       date: DateTime.now().add(const Duration(days: 2)),
//       timeSlot: '09:00-11:00',
//       duration: 120,
//       price: 9000,
//       discountedPrice: 8550,
//       status: ReservationStatus.reserved,
//       notes: '시험 준비 기도',
//       createdAt: DateTime.now().subtract(const Duration(hours: 3)),
//       updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
//     ),
//     Reservation(
//       id: 'reservation_5',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_5',
//       branchName: '강동 기도실',
//       spaceId: 'space_9',
//       spaceName: '가족 기도실 I',
//       date: DateTime.now().add(const Duration(days: 3)),
//       timeSlot: '14:00-16:00',
//       duration: 120,
//       price: 20000,
//       discountedPrice: 19000,
//       status: ReservationStatus.reserved,
//       notes: '가족 기도 시간',
//       createdAt: DateTime.now().subtract(const Duration(hours: 1)),
//       updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
//     ),
//     Reservation(
//       id: 'reservation_6',
//       userId: 'user_1',
//       userName: '김기도',
//       branchId: 'branch_6',
//       branchName: '부산해운대 기도실',
//       spaceId: 'space_11',
//       spaceName: '프리미엄 바다뷰 기도실 K',
//       date: DateTime.now().add(const Duration(days: 7)),
//       timeSlot: '10:00-12:00',
//       duration: 120,
//       price: 16000,
//       discountedPrice: 15200,
//       status: ReservationStatus.reserved,
//       notes: '부산 여행 중 기도',
//       createdAt: DateTime.now().subtract(const Duration(days: 1)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 1)),
//     ),
//   ];

//   // 멤버십 데이터

//   // 커뮤니티 데이터 (지점별)
//   static final List<Post> posts = [
//     Post(
//       id: 'post_1',
//       title: '강남 기도실 이용 후기',
//       content:
//           '강남 기도실을 처음 이용해봤는데 정말 좋았습니다. 조용하고 깔끔한 환경에서 기도할 수 있어서 만족스러웠어요. 특히 1인 기도실 A가 추천합니다!',
//       authorId: 'user_1',
//       authorName: '김기도',
//       branchId: 'branch_1',
//       branchName: '강남 기도실',
//       viewCount: 45,
//       commentCount: 3,
//       comments: [
//         Comment(
//           id: 'comment_1',
//           postId: 'post_1',
//           authorId: 'user_2',
//           authorName: '이기도',
//           content: '저도 강남 기도실 이용해봤는데 정말 좋았어요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 5)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
//         ),
//         Comment(
//           id: 'comment_2',
//           postId: 'post_1',
//           authorId: 'user_3',
//           authorName: '박기도',
//           content: '다음에 저도 가보고 싶네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 3)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 1)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 1)),
//     ),
//     Post(
//       id: 'post_2',
//       title: '홍대 기도실 24시간 운영',
//       content:
//           '홍대 기도실이 24시간 운영된다고 해서 늦은 시간에 가봤는데 정말 편리했어요. 밤늦게도 기도할 수 있어서 좋습니다.',
//       authorId: 'user_2',
//       authorName: '이기도',
//       branchId: 'branch_2',
//       branchName: '홍대 기도실',
//       viewCount: 32,
//       commentCount: 1,
//       comments: [
//         Comment(
//           id: 'comment_3',
//           postId: 'post_2',
//           authorId: 'user_1',
//           authorName: '김기도',
//           content: '24시간 운영이라니 정말 좋네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 2)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 2)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 2)),
//     ),
//     Post(
//       id: 'post_3',
//       title: '부산 해운대 기도실 바다 전망',
//       content:
//           '부산 여행 중에 해운대 기도실을 이용했는데, 바다가 보이는 기도실이라서 정말 특별했어요. 기도하면서 바다를 바라보니 마음이 평화로워졌습니다.',
//       authorId: 'user_3',
//       authorName: '박기도',
//       branchId: 'branch_3',
//       branchName: '부산 해운대 기도실',
//       viewCount: 28,
//       commentCount: 2,
//       comments: [
//         Comment(
//           id: 'comment_4',
//           postId: 'post_3',
//           authorId: 'user_1',
//           authorName: '김기도',
//           content: '바다 전망이라니 정말 멋지네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 1)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
//         ),
//         Comment(
//           id: 'comment_5',
//           postId: 'post_3',
//           authorId: 'user_2',
//           authorName: '이기도',
//           content: '부산 가면 꼭 가보고 싶어요!',
//           createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
//           updatedAt: DateTime.now().subtract(const Duration(minutes: 30)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 3)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 3)),
//     ),
//     Post(
//       id: 'post_4',
//       title: '기도실 이용 팁 공유',
//       content:
//           '여러 지점을 이용해보면서 알게 된 팁을 공유합니다. 1. 예약은 미리 하는 것이 좋아요. 2. 조용한 시간대는 오전이나 늦은 밤입니다. 3. 멤버십 할인을 활용하세요!',
//       authorId: 'user_1',
//       authorName: '김기도',
//       branchId: null,
//       branchName: null,
//       viewCount: 67,
//       commentCount: 5,
//       comments: [
//         Comment(
//           id: 'comment_6',
//           postId: 'post_4',
//           authorId: 'user_2',
//           authorName: '이기도',
//           content: '정말 유용한 팁이네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 4)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
//         ),
//         Comment(
//           id: 'comment_7',
//           postId: 'post_4',
//           authorId: 'user_3',
//           authorName: '박기도',
//           content: '멤버십 할인 정말 좋죠!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 3)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 4)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 4)),
//     ),
//     Post(
//       id: 'post_5',
//       title: '대치 기도실 스터디 환경',
//       content:
//           '대치 기도실의 스터디 기도실을 이용했는데 정말 좋았어요. 학생들이 공부하면서 기도하기에 딱 좋은 환경이었습니다. 특히 조용하고 집중하기 좋았어요.',
//       authorId: 'user_2',
//       authorName: '이기도',
//       branchId: 'branch_4',
//       branchName: '대치 기도실',
//       viewCount: 23,
//       commentCount: 2,
//       comments: [
//         Comment(
//           id: 'comment_8',
//           postId: 'post_5',
//           authorId: 'user_1',
//           authorName: '김기도',
//           content: '저도 대치 지점 이용해봤는데 정말 좋았어요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 2)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 5)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 5)),
//     ),
//     Post(
//       id: 'post_6',
//       title: '강동 기도실 가족 친화적',
//       content:
//           '강동 기도실의 가족 기도실을 이용했는데 정말 넓고 편안했어요. 가족이 함께 기도하기에 최적의 환경이었습니다. 특히 아이들이 있어도 안전하고 좋았어요.',
//       authorId: 'user_3',
//       authorName: '박기도',
//       branchId: 'branch_5',
//       branchName: '강동 기도실',
//       viewCount: 18,
//       commentCount: 1,
//       comments: [
//         Comment(
//           id: 'comment_9',
//           postId: 'post_6',
//           authorId: 'user_1',
//           authorName: '김기도',
//           content: '가족 기도실이라니 정말 좋네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 1)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 6)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 6)),
//     ),
//     Post(
//       id: 'post_7',
//       title: '부산해운대 기도실 프리미엄 경험',
//       content:
//           '부산해운대 기도실의 프리미엄 바다뷰 기도실을 이용했는데 정말 특별했어요. 바다를 바라보며 기도하니 마음이 평화로워졌습니다. 가격대비 정말 만족스러웠어요.',
//       authorId: 'user_1',
//       authorName: '김기도',
//       branchId: 'branch_6',
//       branchName: '부산해운대 기도실',
//       viewCount: 34,
//       commentCount: 3,
//       comments: [
//         Comment(
//           id: 'comment_10',
//           postId: 'post_7',
//           authorId: 'user_2',
//           authorName: '이기도',
//           content: '바다 전망이라니 정말 멋지네요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 3)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
//         ),
//         Comment(
//           id: 'comment_11',
//           postId: 'post_7',
//           authorId: 'user_3',
//           authorName: '박기도',
//           content: '부산 가면 꼭 가보고 싶어요!',
//           createdAt: DateTime.now().subtract(const Duration(hours: 2)),
//           updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
//         ),
//       ],
//       createdAt: DateTime.now().subtract(const Duration(days: 7)),
//       updatedAt: DateTime.now().subtract(const Duration(days: 7)),
//     ),
//   ];

//   // 시간대 데이터
//   static final List<TimeSlot> timeSlots = [
//     TimeSlot(id: 'time_1', time: '06:00-08:00', isAvailable: true),
//     TimeSlot(id: 'time_2', time: '08:00-10:00', isAvailable: true),
//     TimeSlot(id: 'time_3', time: '10:00-12:00', isAvailable: false),
//     TimeSlot(id: 'time_4', time: '12:00-14:00', isAvailable: true),
//     TimeSlot(id: 'time_5', time: '14:00-16:00', isAvailable: true),
//     TimeSlot(id: 'time_6', time: '16:00-18:00', isAvailable: false),
//     TimeSlot(id: 'time_7', time: '18:00-20:00', isAvailable: true),
//     TimeSlot(id: 'time_8', time: '20:00-22:00', isAvailable: true),
//   ];
// }
